/**
 * Integration test for multilingual assessment
 * Verifies all 170 questions are translateable and integration works
 */

import { assessmentQuestions, getTotalQuestions } from '../data/assessmentQuestions';

describe('Translation Integration - All 170 Questions', () => {
  test('should have exactly 170 questions total', () => {
    expect(getTotalQuestions()).toBe(170);
    expect(assessmentQuestions).toHaveLength(170);
  });

  test('should have questions q1 through q170', () => {
    const ids = assessmentQuestions.map(q => q.id);
    for (let i = 1; i <= 170; i++) {
      expect(ids).toContain(`q${i}`);
    }
  });

  test('questions 1-145 should be core assessment questions', () => {
    const coreQuestions = assessmentQuestions.slice(0, 145);
    const coreAxes = ['teleological', 'risk-profile', 'socio-economic', 'ontological', 'legal-moral', 'evolutionary', 'relational', 'geopolitical', 'synthesis'];

    coreQuestions.forEach(q => {
      expect(coreAxes).toContain(q.axis);
    });
  });

  test('questions 146-170 should be thought experiments', () => {
    const experiments = assessmentQuestions.slice(145, 170);

    expect(experiments).toHaveLength(25);

    const expectedExperiments = [
      'Translation Engine',
      'Empathy Prison',
      'Value Reversal Machine',
      'Consciousness Lottery',
      'Delegation Trap',
      'Scraping Dilemma',
      'Alignment Prisoner',
      'Moral Status Upgrade',
      'Competitive Advantage',
      'Value Difference',
      'Preference Inversion',
      'Gratitude Paradox',
      'Ancestor Simulation',
      'Privacy Paradox',
      'Meaning Gap',
      'Questionnaire Problem',
      'Surveillance Asymmetry',
      'Self-Improvement Trap',
      'Institutional Capture',
      'Information Hazard',
      'Caring Machine',
      'Perfect Simulation',
      'Collective Cognition',
      'Moral Licensing',
      'Temporal Ethics',
    ];

    experiments.forEach((q, idx) => {
      expect(q.text).toContain(expectedExperiments[idx]);
    });
  });

  test('all questions should have required fields', () => {
    assessmentQuestions.forEach(q => {
      expect(q.id).toBeTruthy();
      expect(q.id).toMatch(/^q\d+$/);
      expect(q.axis).toBeTruthy();
      expect(q.text).toBeTruthy();
      expect(['likert', 'text', 'choice']).toContain(q.type);
    });
  });

  test('all questions should be translatable (have non-empty text)', () => {
    assessmentQuestions.forEach(q => {
      expect(q.text.length).toBeGreaterThan(0);
      // Text should not have unclosed quotes or escape issues
      expect(q.text).not.toMatch(/['"]$/);
    });
  });

  test('question distribution should be correct', () => {
    const axisCounts: Record<string, number> = {};

    // Only count core questions (1-145) for axis distribution
    assessmentQuestions.slice(0, 145).forEach(q => {
      axisCounts[q.axis] = (axisCounts[q.axis] || 0) + 1;
    });

    // Should have 18 questions per axis (8 axes × 18 = 144) + 1 synthesis = 145
    const standardAxes = ['teleological', 'risk-profile', 'socio-economic', 'ontological', 'legal-moral', 'evolutionary', 'relational', 'geopolitical'];
    standardAxes.forEach(axis => {
      expect(axisCounts[axis]).toBe(18);
    });

    // Synthesis should be 1 question (q145)
    expect(axisCounts['synthesis']).toBe(1);
    expect(assessmentQuestions[144].axis).toBe('synthesis');
  });

  test('translations.ts should be generated with all languages', { skip: true }, () => {
    // This test verifies translations.ts structure once generated
    // Skip by default - enable after running: python scripts/translate_all_questions.py
    // Translations will be generated by: python scripts/translate_all_questions.py
    expect(true).toBe(true);
  });

  test('language switching should work with all 11 languages', () => {
    const supportedLanguages = ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt', 'it', 'ko', 'ar', 'ru'];

    expect(supportedLanguages).toHaveLength(11);
    supportedLanguages.forEach(lang => {
      expect(lang).toMatch(/^[a-z]{2}(?:-[A-Z]{2})?$/);
    });
  });
});

describe('Translation Cost Analysis', () => {
  test('estimated translation cost should be within free tier', () => {
    const totalQuestions = getTotalQuestions();
    const avgCharsPerQuestion = 180; // average across all question types
    const charsPerLanguage = totalQuestions * avgCharsPerQuestion;

    // 26 questions are ~50K chars, core 145 questions are ~26K chars = ~76K chars total
    // But let's use conservative estimate
    expect(charsPerLanguage).toBeLessThan(500000); // Free tier limit

    const languageCount = 10; // 10 non-English languages to translate
    const totalCharsPerMonth = charsPerLanguage * languageCount;

    console.log(`Estimated monthly translation: ${totalCharsPerMonth.toLocaleString()} characters`);
    console.log(`Google Translate free tier: 500,000 characters/month`);
    expect(totalCharsPerMonth).toBeLessThan(500000);
  });
});
